spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cloud_storage
    username: cloud_user
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # Używamy Liquibase zamiast Hibernate do zarządzania schematem
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml