apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-storage-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          {{- range .Values.applications }}
          - path: /api/{{ .name }}
            pathType: Prefix
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .port }}
          {{- end }}
---
