apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  labels:
    app: postgres
data:
  01-schema.sql: |
    CREATE TABLE users (
        id BIGSERIAL PRIMARY KEY,
        username VARCHAR(255) UNIQUE NOT NULL,
        password TEXT NOT NULL,
        password_hash TEXT,
        email VARCHAR(255) UNIQUE,
        role VARCHAR(50) DEFAULT 'USER',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE file (
        id SERIAL PRIMARY KEY,
        file_name VARCHAR(255),
        file_path VARCHAR(255),
        content BYTEA,
        size BIGINT,
        user_id BIGINT REFERENCES users(id),
        uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE logs (
        id BIGSERIAL PRIMARY KEY,
        user_id BIGINT REFERENCES users(id),
        action VARCHAR(255) NOT NULL,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX idx_file_user_id ON file(user_id);
    CREATE INDEX idx_logs_user_id ON logs(user_id);

  02-init.sql: |
    INSERT INTO users (username, password, password_hash, email, role) 
    VALUES 
    ('test_user', 'hashed_password_1', 'hashed_password_1', 'user1@example.com', 'ADMIN'),
    ('demo_user', 'hashed_password_2', 'hashed_password_2', 'user2@example.com', 'USER');

    INSERT INTO file (user_id, file_name, file_path, size, content) 
    VALUES 
    (1, 'file1.txt', '/uploads/file1.txt', 1024, NULL),
    (1, 'file2.txt', '/uploads/file2.txt', 2048, NULL),
    (2, 'file3.txt', '/uploads/file3.txt', 512, NULL);

    INSERT INTO logs (user_id, action) 
    VALUES 
    (1, 'User login'),
    (2, 'File upload'),
    (1, 'File deletion');
