apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  labels:
    app: postgres
data:
  01-schema.sql: |
    {{ .Files.Get "backend/config/database/01-schema.sql" | indent 4 }}
  02-init.sql: |
    {{ .Files.Get "backend/config/database/02-init.sql" | indent 4 }}
