{{- if not .Values.postgres.useExistingPVC }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: postgres-pvc
  annotations:
    meta.helm.sh/release-name: cloud-storage
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storage }}
---
{{- end }}
