databaseChangeLog: 
  - changeSet:
      id: 1
      author: initial
      changes:
        - createTable:
            tableName: users
            columns:
              - column:
                  name: id
                  type: BIGSERIAL
                  constraints:
                    primaryKey: true
              - column:
                  name: username
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: password
                  type: TEXT
                  constraints:
                    nullable: false
              - column:
                  name: password_hash
                  type: TEXT
              - column:
                  name: email
                  type: VARCHAR(255)
                  constraints:
                    unique: true
              - column:
                  name: role
                  type: VARCHAR(50)
                  defaultValue: USER
              - column:
                  name: created_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
  - changeSet:
      id: 2
      author: initial
      changes:
        - createTable:
            tableName: file
            columns:
              - column:
                  name: id
                  type: BIGSERIAL
                  constraints:
                    primaryKey: true
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: true
                    foreignKeyName: file_user_id_fk
                    references: users(id)
                    onDelete: CASCADE
              - column:
                  name: file_name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: file_path
                  type: TEXT
                  constraints:
                    nullable: false
              - column:
                  name: size
                  type: BIGINT
              - column:
                  name: content
                  type: BYTEA
                  constraints:
                    nullable: true
              - column:
                  name: uploaded_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
  - changeSet:
      id: 3
      author: initial
      changes:
        - createTable:
            tableName: logs
            columns:
              - column:
                  name: id
                  type: BIGSERIAL
                  constraints:
                    primaryKey: true
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    foreignKeyName: fk_logs_users
                    references: users(id)
              - column:
                  name: action
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: timestamp
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
