postgres:
  name: postgres
  replicas: 1
  image: postgres:17
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  user: cloud_user
  password: root
  database: cloud_storage
  useExistingPVC: false
  pvc:
    storage: 10Gi

applications:
  - name: admin-panel
    image: lukaszandzej/cloud-storage-admin-panel:latest
    replicas: 1
    port: 8081

  - name: auth-service
    image: lukaszandzej/cloud-storage-auth-service:latest
    replicas: 1
    port: 8082

  - name: file-service
    image: lukaszandzej/cloud-storage-file-service:latest
    replicas: 1
    port: 8083

  - name: payment-service
    image: lukaszandzej/cloud-storage-payment-service:latest
    replicas: 1
    port: 8084

  - name: support-service
    image: lukaszandzej/cloud-storage-support-service:latest
    replicas: 1
    port: 8085

  - name: frontend
    image: lukaszandzej/cloud-storage-frontend:latest
    replicas: 1
    port: 8080

ingress:
  enabled: true
  hostname: cloud-storage.local

serviceAccount:
  create: false
  name: default

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
