postgres:
  name: postgres
  replicas: 1
  image: postgres:17
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  user: cloud_user
  password: root
  database: cloud_storage
  useExistingPVC: false
  pvc:
    storage: 10Gi

applications:
  - name: admin-panel
    image: lukaszandzej/cloud-storage-admin-panel:latest
    replicas: 1
    port: 8081
    env:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: cloud_storage
      DB_USER: cloud_user
      DB_PASSWORD: root

  - name: auth-service
    image: lukaszandzej/cloud-storage-auth-service:latest
    replicas: 1
    port: 8080  # Zmiana na 8080 zgodnie z logami
    env:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: cloud_storage
      DB_USER: cloud_user
      DB_PASSWORD: root
      SERVER_PORT: 8080  # Dodanie zmiennej środowiskowej

  - name: file-service
    image: lukaszandzej/cloud-storage-file-service:latest
    replicas: 1
    port: 8080
    env:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: cloud_storage
      DB_USER: cloud_user
      DB_PASSWORD: root

  - name: payment-service
    image: lukaszandzej/cloud-storage-payment-service:latest
    replicas: 1
    port: 8084
    env:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: cloud_storage
      DB_USER: cloud_user
      DB_PASSWORD: root

  - name: support-service
    image: lukaszandzej/cloud-storage-support-service:latest
    replicas: 1
    port: 8085
    env:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: cloud_storage
      DB_USER: cloud_user
      DB_PASSWORD: root

  - name: frontend
    image: lukaszandzej/cloud-storage-frontend:latest
    replicas: 1
    port: 8080
    env:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: cloud_storage
      DB_USER: cloud_user
      DB_PASSWORD: root
      FILE_SERVICE_URL: http://file-service.default.svc.cluster.local:8080
      AUTH_SERVICE_URL: http://auth-service.default.svc.cluster.local:8080  # Poprawiony URL

ingress:
  enabled: true
  hostname: cloud-storage.local

serviceAccount:
  create: false
  name: default

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
