name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Services
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [auth-service, admin-panel, file-service, payment-service, support-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test ${{ matrix.service }}
        working-directory: backend
        run: |
          mvn clean install -Dspring.profiles.active=test -pl services/${{ matrix.service }} -am

  docker-build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [auth-service, admin-panel, file-service, payment-service, support-service, frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for backend services
        if: matrix.service != 'frontend'
        working-directory: backend
        run: |
          DOCKER_IMAGE_NAME="lukaszandzej/cloud-storage-${{ matrix.service }}"
          TAG="${{ github.sha }}"
          docker build -t $DOCKER_IMAGE_NAME:$TAG -t $DOCKER_IMAGE_NAME:latest -f services/${{ matrix.service }}/Dockerfile .

      - name: Build Docker image for frontend
        if: matrix.service == 'frontend'
        working-directory: frontend
        run: |
          DOCKER_IMAGE_NAME="lukaszandzej/cloud-storage-frontend"
          TAG="${{ github.sha }}"
          docker build -t $DOCKER_IMAGE_NAME:$TAG -t $DOCKER_IMAGE_NAME:latest .

      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          DOCKER_IMAGE_NAME="lukaszandzej/cloud-storage-${{ matrix.service }}"
          TAG="${{ github.sha }}"
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push $DOCKER_IMAGE_NAME:$TAG
          docker push $DOCKER_IMAGE_NAME:latest
